import fs from 'node:fs/promises';
import path from 'node:path';
import puppeteer from 'puppeteer-core';
import { findBrowser } from './browser.mjs';
import { withVite } from './server.mjs';

const root = path.resolve(new URL('..', import.meta.url).pathname.replace(/^\/(?:[A-Za-z]:)/, (value) => value.slice(1)));
const shots = path.join(root, 'shots');
await fs.mkdir(shots, { recursive: true });

await withVite(async (url) => {
  const browser = await puppeteer.launch({ executablePath: findBrowser(), headless: true, args: ['--no-sandbox', '--enable-unsafe-swiftshader'], defaultViewport: { width: 1440, height: 900, deviceScaleFactor: 1 } });
  const bootPage = await browser.newPage();
  await bootPage.setJavaScriptEnabled(false);
  await bootPage.goto(url, { waitUntil: 'domcontentloaded' });
  await bootPage.screenshot({ path: path.join(shots, 'boot.png') });
  await bootPage.close();
  const page = await browser.newPage();
  await page.goto(url, { waitUntil: 'networkidle0' });
  await page.waitForFunction(() => window.__slotReady === true, { timeout: 15000 });
  await page.waitForFunction(() => document.body.classList.contains('app-ready'), { timeout: 15000 });
  await new Promise((resolve) => setTimeout(resolve, 1200));
  await page.screenshot({ path: path.join(shots, 'attract.png') });
  await page.evaluate(() => window.__slot.start());
  await new Promise((resolve) => setTimeout(resolve, 500));
  await page.screenshot({ path: path.join(shots, 'play.png') });
  await page.click('#settingsBtn');
  await page.select('#graphicsQuality', 'cinematic');
  await page.click('#fpsToggle');
  await new Promise((resolve) => setTimeout(resolve, 700));
  await page.screenshot({ path: path.join(shots, 'graphics-settings.png') });
  await page.keyboard.press('Escape');
  await new Promise((resolve) => setTimeout(resolve, 250));
  await page.screenshot({ path: path.join(shots, 'cinematic-aa.png') });
  await page.click('#paytableBtn');
  await new Promise((resolve) => setTimeout(resolve, 350));
  await page.screenshot({ path: path.join(shots, 'paylines.png') });
  await page.keyboard.press('Escape');
  await new Promise((resolve) => setTimeout(resolve, 200));
  await page.evaluate(() => window.__slot.addCoin());
  await new Promise((resolve) => setTimeout(resolve, 420));
  await page.screenshot({ path: path.join(shots, 'coin-route.png') });
  await page.evaluate(() => { window.__slot.force(['nuraliev', 'nuraliev', 'nuraliev']); window.__slot.spin(); });
  await page.waitForFunction(() => window.__slot.getState().mode === 'idle', { timeout: 8000 });
  await new Promise((resolve) => setTimeout(resolve, 250));
  await page.screenshot({ path: path.join(shots, 'win.png') });
  await page.setViewport({ width: 390, height: 844, deviceScaleFactor: 1 });
  await page.goto(url, { waitUntil: 'networkidle0' });
  await page.waitForFunction(() => window.__slotReady === true, { timeout: 15000 });
  await page.evaluate(() => window.__slot.start());
  await new Promise((resolve) => setTimeout(resolve, 500));
  await page.screenshot({ path: path.join(shots, 'mobile.png') });
  await browser.close();
  console.log(`Скриншоты: ${shots}`);
});
